version: 2

sources:
  - name: tennis_api  # Name of your source
    database: 'tennis'
    schema: 'main'
    tables:
      - name: tournaments   # Name of the source table
        description: "Table containing tournament data."
      - name: leagues
      - name: rounds
      - name: seasons
      - name: matches
      - name: match_statistics