WITH final AS (
    SELECT
        id as match_id,
        tournament_id,
        season_id,
        round_id,
        arena_id,
        home_team_id,
        away_team_id,
        class_id,
        league_id,
        name AS match_name,
        first_to_serve,
        ground_type,
        tournament_name,
        tournament_importance,
        season_name,
        status_type,
        arena_name,
        arena_hash_image,
        home_team_name,
        home_team_hash_image,
        away_team_name,
        away_team_hash_image,
        specific_start_time,
        start_time,
        duration,
        class_name,
        class_hash_image,
        league_name,
        league_hash_image,
        round_name,
        status,
        status_reason,
        home_team_score_current,
        home_team_score_display,
        home_team_score_set_1,
        home_team_score_set_2,
        home_team_score_set_3,
        home_team_score_set_4,
        home_team_score_set_5,
        away_team_score_current,
        away_team_score_display,
        away_team_score_set_1,
        away_team_score_set_2,
        away_team_score_set_3,
        away_team_score_set_4,
        away_team_score_set_5,
        time_set_1,
        time_set_2,
        time_set_3,
        time_set_4,
        time_set_5,   
    FROM 
        {{ source("tennis_api", "matches")}}
)

SELECT * FROM final